SET NAMES 'utf8';
CREATE DATABASE IF NOT EXISTS restapi
  CHARACTER SET utf8
  COLLATE utf8_general_ci;
  USE restapi;

CREATE TABLE IF NOT EXISTS users(
  USER_ID INT AUTO_INCREMENT,
  USER_NAME VARCHAR(20) NOT NULL ,
  PRIMARY KEY (USER_ID)
);
INSERT  IGNORE INTO users(USER_ID,USER_NAME)VALUES (1,'VASYA');
INSERT  IGNORE INTO users(USER_ID,USER_NAME)VALUES (2,'PETYA');